import Foundation
import CryptoKit

public enum ClipKind: String, Codable, CaseIterable, Sendable {
    case text, link, image, file
    public var title: String { switch self { case .text: "Text"; case .link: "Links"; case .image: "Images"; case .file: "Files" } }
    public var symbol: String { switch self { case .text: "text.alignleft"; case .link: "link"; case .image: "photo"; case .file: "doc" } }
}
public struct Representation: Codable, Equatable, Sendable {
    public var type: String
    public var data: Data
    public init(type: String, data: Data) { self.type = type; self.data = data }
}
public struct Clip: Codable, Identifiable, Sendable {
    public var id: UUID
    public var createdAt: Date
    public var lastCopiedAt: Date
    public var source: String
    public var sourceBundle: String
    public var kind: ClipKind
    public var text: String
    public var items: [[Representation]]
    public var pinned: Bool
    public var title: String {
        let line = text.split(whereSeparator: \.isNewline).first.map(String.init) ?? ""
        return line.isEmpty ? (kind == .image ? "Copied image" : "Clipboard item") : String(line.prefix(160))
    }
    public var byteCount: Int { items.flatMap { $0 }.reduce(0) { $0 + $1.data.count } }
    public var fingerprint: String {
        var hash = SHA256()
        for item in items {
            hash.update(data: Data("item\0".utf8))
            for rep in item.sorted(by: { $0.type < $1.type }) {
                hash.update(data: Data("\(rep.type.utf8.count):\(rep.type):\(rep.data.count):".utf8))
                hash.update(data: rep.data)
            }
        }
        return hash.finalize().map { String(format: "%02x", $0) }.joined()
    }
    public init(id: UUID = UUID(), createdAt: Date = Date(), source: String, sourceBundle: String = "", kind: ClipKind, text: String, items: [[Representation]], pinned: Bool = false) {
        self.id = id; self.createdAt = createdAt; self.lastCopiedAt = createdAt; self.source = source; self.sourceBundle = sourceBundle
        self.kind = kind; self.text = text; self.items = items; self.pinned = pinned
    }
    public func matches(_ query: String) -> Bool {
        if query.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty { return true }
        let haystack = "\(text) \(source) \(kind.title)".folding(options: [.diacriticInsensitive, .caseInsensitive], locale: .current)
        return query.folding(options: [.diacriticInsensitive, .caseInsensitive], locale: .current).split(whereSeparator: \.isWhitespace).allSatisfy { haystack.contains($0) }
    }
}
public enum HistoryPolicy {
    public static let sensitiveTypes: Set<String> = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword", "com.typeit4me.clipping", "com.stash.restored"]
    public static func shouldCapture(types: [String], sourceBundle: String, excluded: [String]) -> Bool {
        Set(types).isDisjoint(with: sensitiveTypes) && !excluded.contains { !$0.isEmpty && sourceBundle.caseInsensitiveCompare($0) == .orderedSame }
    }
    public static func retained(_ clips: [Clip], days: Int, limit: Int, maxBytes: Int, now: Date = Date()) -> [Clip] {
        let cutoff = now.addingTimeInterval(-Double(days) * 86400)
        let pinned = clips.filter(\.pinned)
        var bytes = pinned.reduce(0) { $0 + $1.byteCount }
        var result = pinned
        for clip in clips.filter({ !$0.pinned }).sorted(by: { $0.lastCopiedAt > $1.lastCopiedAt }) {
            guard days == 0 || clip.lastCopiedAt >= cutoff, result.count < max(limit, pinned.count), bytes + clip.byteCount <= maxBytes else { continue }
            result.append(clip); bytes += clip.byteCount
        }
        return result.sorted { $0.lastCopiedAt > $1.lastCopiedAt }
    }
}
public enum VaultCodec {
    public static func seal(_ clip: Clip, key: SymmetricKey) throws -> Data {
        guard let data = try AES.GCM.seal(JSONEncoder().encode(clip), using: key).combined else { throw CocoaError(.fileWriteUnknown) }
        return data
    }
    public static func open(_ data: Data, key: SymmetricKey) throws -> Clip {
        try JSONDecoder().decode(Clip.self, from: AES.GCM.open(AES.GCM.SealedBox(combined: data), using: key))
    }
}
